### ISSUE TITLE
Support Tickets creating Sub-Projects of an Support-Project?

### ISSUE THREAD

**Issue by danielkoerner** [varioous/openproject-ticket-system#5]
Hello, i have some different questions about this script:

Is it possible that this script will create a subproject of another "bigger" Support project for every ticket?

- That would prevent that one user will see support tickets of other users
- It would also allow a better overview for systems where openproject is used mainly for project management

Or even better (in my opinion) is it possible that this script generates just tasks in a support project, leaving "customers" out of the system?

I really don't want to mess the structure up as i'm using it for project management - but surely openproject would be enough for my use case - if one customer doesn't see other tickets of other customers.

**Comment by varioous** [comment]
Hi Daniel,

currently every project is created as "main" project, but could be quite easily customized to creat every new project as subproject of a specific mainproject. Currently as you already described, for every user a new project is created (if not already exist) so that only this user can see the tickets.

Also your second point (leaving "customers" out) could be easily done, we already do it for job applications, where every application creates a ticket in the same project without user involvment.

Best regards,
Harald

**Comment by danielkoerner** [comment]
Hi Harald, thank you very much for the explanation and fast reply.

This info is exactly what i needed to make sure what i need to rewrite.

I will try to adapt it to my needs and test it, thanks!

Btw: My goal was using openproject for internal project management - and including a small internal user support platform, which is seperated right now (openproject and jira service management, which is overpowered and pricy)
We used OTRS in the past - but this is also very overpowered (and slow)

**Comment by varioous** [comment]
HI Daniel,

you are welcome. Please let me know if you need help or later about the experience with the script and possible improvements.

Best wishes from Wels,
Harald
